import type { SerialNode, SerialEdge } from "@/types";

export interface ProjectTemplate {
  id: string;
  name: string;
  description: string;
  tags: string[];
  nodes: SerialNode[];
  edges: SerialEdge[];
}

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  /* ── Simple Dialogue ─────────────────────────────────────── */
  {
    id: "simple-dialogue",
    name: "Simple Dialogue",
    description: "Two characters talking",
    tags: ["basic", "linear"],
    nodes: [
      {
        id: "sd-hero",
        type: "character",
        position: { x: 0, y: 0 },
        data: {
          name: "Hero",
          dialogue: "Excuse me — do you know the way to the market district?",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "sd-guard",
        type: "character",
        position: { x: 0, y: 160 },
        data: {
          name: "Guard",
          dialogue: "Straight ahead, past the fountain. Can't miss it.",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "sd-end",
        type: "action",
        position: { x: 0, y: 320 },
        data: {
          actionType: "end",
          label: "End Conversation",
          attributeSchema: [],
          attributes: {},
        },
      },
    ] as SerialNode[],
    edges: [
      {
        id: "sd-e1",
        source: "sd-hero",
        target: "sd-guard",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "sd-e2",
        source: "sd-guard",
        target: "sd-end",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
    ] as SerialEdge[],
  },

  /* ── Choice Branch ───────────────────────────────────────── */
  {
    id: "choice-branch",
    name: "Choice Branch",
    description: "Player chooses a response",
    tags: ["branch", "choice"],
    nodes: [
      {
        id: "cb-npc",
        type: "character",
        position: { x: 0, y: 0 },
        data: {
          name: "Merchant",
          dialogue:
            "I have a rare map that leads to ancient ruins. Interested?",
          emotion: "happy",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cb-branch",
        type: "action",
        position: { x: 0, y: 160 },
        data: {
          actionType: "branch",
          label: "Player Response",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cb-yes",
        type: "character",
        position: { x: -200, y: 320 },
        data: {
          name: "Player",
          dialogue: "Absolutely. How much are you asking?",
          emotion: "happy",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cb-no",
        type: "character",
        position: { x: 200, y: 320 },
        data: {
          name: "Player",
          dialogue: "Not today. I have more pressing matters.",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cb-npc-yes",
        type: "character",
        position: { x: -200, y: 480 },
        data: {
          name: "Merchant",
          dialogue:
            "Only fifty gold — a steal for what waits inside those ruins!",
          emotion: "happy",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cb-npc-no",
        type: "character",
        position: { x: 200, y: 480 },
        data: {
          name: "Merchant",
          dialogue: "A shame. Come back when you change your mind.",
          emotion: "sad",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cb-end-a",
        type: "action",
        position: { x: -200, y: 640 },
        data: {
          actionType: "end",
          label: "End — accepted offer",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cb-end-b",
        type: "action",
        position: { x: 200, y: 640 },
        data: {
          actionType: "end",
          label: "End — declined offer",
          attributeSchema: [],
          attributes: {},
        },
      },
    ] as SerialNode[],
    edges: [
      {
        id: "cb-e1",
        source: "cb-npc",
        target: "cb-branch",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "cb-e2",
        source: "cb-branch",
        target: "cb-yes",
        type: "dialogue",
        data: { optionText: "I'm interested.", conditions: {}, metadata: {} },
      },
      {
        id: "cb-e3",
        source: "cb-branch",
        target: "cb-no",
        type: "dialogue",
        data: { optionText: "Not right now.", conditions: {}, metadata: {} },
      },
      {
        id: "cb-e4",
        source: "cb-yes",
        target: "cb-npc-yes",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "cb-e5",
        source: "cb-no",
        target: "cb-npc-no",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "cb-e6",
        source: "cb-npc-yes",
        target: "cb-end-a",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "cb-e7",
        source: "cb-npc-no",
        target: "cb-end-b",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
    ] as SerialEdge[],
  },

  /* ── Combat Banter ───────────────────────────────────────── */
  {
    id: "combat-banter",
    name: "Combat Banter",
    description: "Fight with dialogue tree",
    tags: ["combat", "branch", "triggers"],
    nodes: [
      {
        id: "cm-enemy",
        type: "character",
        position: { x: 0, y: 0 },
        data: {
          name: "Warlord Kael",
          dialogue: "You dare challenge me alone? How refreshingly foolish.",
          emotion: "angry",
          portrait: "",
          attributeSchema: [
            { id: "cm-attr-hp", name: "HP", type: "number", defaultValue: 100 },
          ],
          attributes: { "cm-attr-hp": 100 },
        },
      },
      {
        id: "cm-hero",
        type: "character",
        position: { x: 0, y: 160 },
        data: {
          name: "Hero",
          dialogue: "I've faced worse. Let's end this quickly.",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cm-branch",
        type: "action",
        position: { x: 0, y: 320 },
        data: {
          actionType: "branch",
          label: "Tactical Choice",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cm-fight",
        type: "character",
        position: { x: -240, y: 480 },
        data: {
          name: "Hero",
          dialogue: "No more words. Draw your weapon!",
          emotion: "angry",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cm-flee",
        type: "character",
        position: { x: 0, y: 480 },
        data: {
          name: "Hero",
          dialogue: "I need a better position. Fall back!",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cm-talk",
        type: "character",
        position: { x: 240, y: 480 },
        data: {
          name: "Hero",
          dialogue: "Wait — there's no reason we have to do this.",
          emotion: "happy",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cm-trigger-fight",
        type: "action",
        position: { x: -240, y: 640 },
        data: {
          actionType: "trigger",
          label: "Start Combat",
          category: "game",
          event: "QuestStarted",
          params: { flag: "combat_started" },
          executionMode: "immediate",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cm-trigger-flee",
        type: "action",
        position: { x: 0, y: 640 },
        data: {
          actionType: "trigger",
          label: "Retreat",
          category: "game",
          event: "EnemyKilled",
          params: { flag: "player_retreated" },
          executionMode: "immediate",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cm-enemy-talk",
        type: "character",
        position: { x: 240, y: 640 },
        data: {
          name: "Warlord Kael",
          dialogue: "...Interesting. Very well. I will hear you out.",
          emotion: "surprised",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cm-end-a",
        type: "action",
        position: { x: -240, y: 800 },
        data: {
          actionType: "end",
          label: "End — battle begins",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cm-end-b",
        type: "action",
        position: { x: 0, y: 800 },
        data: {
          actionType: "end",
          label: "End — player retreats",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cm-end-c",
        type: "action",
        position: { x: 240, y: 800 },
        data: {
          actionType: "end",
          label: "End — negotiation begins",
          attributeSchema: [],
          attributes: {},
        },
      },
    ] as SerialNode[],
    edges: [
      {
        id: "cm-e1",
        source: "cm-enemy",
        target: "cm-hero",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "cm-e2",
        source: "cm-hero",
        target: "cm-branch",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "cm-e3",
        source: "cm-branch",
        target: "cm-fight",
        type: "dialogue",
        data: { optionText: "Attack!", conditions: {}, metadata: {} },
      },
      {
        id: "cm-e4",
        source: "cm-branch",
        target: "cm-flee",
        type: "dialogue",
        data: { optionText: "Retreat", conditions: {}, metadata: {} },
      },
      {
        id: "cm-e5",
        source: "cm-branch",
        target: "cm-talk",
        type: "dialogue",
        data: { optionText: "Negotiate", conditions: {}, metadata: {} },
      },
      {
        id: "cm-e6",
        source: "cm-fight",
        target: "cm-trigger-fight",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "cm-e7",
        source: "cm-flee",
        target: "cm-trigger-flee",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "cm-e8",
        source: "cm-talk",
        target: "cm-enemy-talk",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "cm-e9",
        source: "cm-trigger-fight",
        target: "cm-end-a",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "cm-e10",
        source: "cm-trigger-flee",
        target: "cm-end-b",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "cm-e11",
        source: "cm-enemy-talk",
        target: "cm-end-c",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
    ] as SerialEdge[],
  },

  /* ── Multi-Branch Story ──────────────────────────────────── */
  {
    id: "multi-branch-story",
    name: "Multi-Branch Story",
    description: "Multiple independent entry points",
    tags: ["start", "multi-entry", "linear"],
    nodes: [
      {
        id: "mb-s1",
        type: "start",
        position: { x: -460, y: 0 },
        data: { name: "Main Story" },
      },
      {
        id: "mb-hero",
        type: "character",
        position: { x: -460, y: 160 },
        data: {
          name: "Hero",
          dialogue: "We finally arrived at the ancient ruins.",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "mb-end1",
        type: "action",
        position: { x: -460, y: 320 },
        data: {
          actionType: "end",
          label: "End — Main Story",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "mb-s2",
        type: "start",
        position: { x: 0, y: 0 },
        data: { name: "Merchant" },
      },
      {
        id: "mb-merchant",
        type: "character",
        position: { x: 0, y: 160 },
        data: {
          name: "Merchant",
          dialogue: "Welcome, traveller. Take a look at my wares.",
          emotion: "happy",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "mb-end2",
        type: "action",
        position: { x: 0, y: 320 },
        data: {
          actionType: "end",
          label: "End — Merchant",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "mb-s3",
        type: "start",
        position: { x: 460, y: 0 },
        data: { name: "Tutorial" },
      },
      {
        id: "mb-guide",
        type: "character",
        position: { x: 460, y: 160 },
        data: {
          name: "Guide",
          dialogue: "Use WASD to move and left-click to interact.",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "mb-end3",
        type: "action",
        position: { x: 460, y: 320 },
        data: {
          actionType: "end",
          label: "End — Tutorial",
          attributeSchema: [],
          attributes: {},
        },
      },
    ] as SerialNode[],
    edges: [
      {
        id: "mb-e1",
        source: "mb-s1",
        target: "mb-hero",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "mb-e2",
        source: "mb-hero",
        target: "mb-end1",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "mb-e3",
        source: "mb-s2",
        target: "mb-merchant",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "mb-e4",
        source: "mb-merchant",
        target: "mb-end2",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "mb-e5",
        source: "mb-s3",
        target: "mb-guide",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "mb-e6",
        source: "mb-guide",
        target: "mb-end3",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
    ] as SerialEdge[],
  },

  /* ── Combat Encounter ────────────────────────────────────── */
  {
    id: "combat-encounter",
    name: "Combat Encounter",
    description: "Start node, audio triggers and combat branching",
    tags: ["start", "trigger", "audio", "branch"],
    nodes: [
      {
        id: "ce-start",
        type: "start",
        position: { x: 0, y: 0 },
        data: { name: "Combat" },
      },
      {
        id: "ce-music",
        type: "action",
        position: { x: 0, y: 160 },
        data: {
          actionType: "trigger",
          label: "Play Battle Music",
          category: "audio",
          event: "PlayMusic",
          params: { track: "battle_theme" },
          executionMode: "immediate",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "ce-hero",
        type: "character",
        position: { x: 0, y: 320 },
        data: {
          name: "Hero",
          dialogue: "Prepare yourself.",
          emotion: "angry",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "ce-branch",
        type: "action",
        position: { x: 0, y: 480 },
        data: {
          actionType: "branch",
          label: "Player Choice",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "ce-fight",
        type: "character",
        position: { x: -200, y: 640 },
        data: {
          name: "Hero",
          dialogue: "I won't back down!",
          emotion: "angry",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "ce-run",
        type: "character",
        position: { x: 200, y: 640 },
        data: {
          name: "Hero",
          dialogue: "This is not my battle today.",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "ce-trig-attack",
        type: "action",
        position: { x: -200, y: 800 },
        data: {
          actionType: "trigger",
          label: "Play Attack Animation",
          category: "animation",
          event: "Attack",
          params: {},
          executionMode: "beforeNext",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "ce-trig-escape",
        type: "action",
        position: { x: 200, y: 800 },
        data: {
          actionType: "trigger",
          label: "Show Escape UI",
          category: "ui",
          event: "ShowEscape",
          params: {},
          executionMode: "immediate",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "ce-end-a",
        type: "action",
        position: { x: -200, y: 960 },
        data: {
          actionType: "end",
          label: "End — Fight",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "ce-end-b",
        type: "action",
        position: { x: 200, y: 960 },
        data: {
          actionType: "end",
          label: "End — Run",
          attributeSchema: [],
          attributes: {},
        },
      },
    ] as SerialNode[],
    edges: [
      {
        id: "ce-e1",
        source: "ce-start",
        target: "ce-music",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "ce-e2",
        source: "ce-music",
        target: "ce-hero",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "ce-e3",
        source: "ce-hero",
        target: "ce-branch",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "ce-e4",
        source: "ce-branch",
        target: "ce-fight",
        type: "dialogue",
        data: { optionText: "Fight", conditions: {}, metadata: {} },
      },
      {
        id: "ce-e5",
        source: "ce-branch",
        target: "ce-run",
        type: "dialogue",
        data: { optionText: "Run", conditions: {}, metadata: {} },
      },
      {
        id: "ce-e6",
        source: "ce-fight",
        target: "ce-trig-attack",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "ce-e7",
        source: "ce-run",
        target: "ce-trig-escape",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "ce-e8",
        source: "ce-trig-attack",
        target: "ce-end-a",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "ce-e9",
        source: "ce-trig-escape",
        target: "ce-end-b",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
    ] as SerialEdge[],
  },

  /* ── Quest System ────────────────────────────────────────── */
  {
    id: "quest-system",
    name: "Quest System",
    description: "Game triggers, branching acceptance and a jump loop",
    tags: ["start", "trigger", "game", "jump", "branch"],
    nodes: [
      {
        id: "qs-start",
        type: "start",
        position: { x: 0, y: 0 },
        data: { name: "Quest" },
      },
      {
        id: "qs-npc1",
        type: "character",
        position: { x: 0, y: 160 },
        data: {
          name: "Village Elder",
          dialogue: "The forest has grown dangerous. Can you help us?",
          emotion: "sad",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "qs-branch",
        type: "action",
        position: { x: 0, y: 320 },
        data: {
          actionType: "branch",
          label: "Player Response",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "qs-accept",
        type: "character",
        position: { x: -200, y: 480 },
        data: {
          name: "Hero",
          dialogue: "I'll do it. Tell me more.",
          emotion: "happy",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "qs-decline",
        type: "character",
        position: { x: 200, y: 480 },
        data: {
          name: "Hero",
          dialogue: "I'm afraid I can't help right now.",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "qs-trig-accept",
        type: "action",
        position: { x: -200, y: 640 },
        data: {
          actionType: "trigger",
          label: "Quest Started",
          category: "game",
          event: "QuestStarted",
          params: { questId: "forest_danger" },
          executionMode: "afterNext",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "qs-npc2",
        type: "character",
        position: { x: -200, y: 800 },
        data: {
          name: "Village Elder",
          dialogue: "Please return with the herbs from the northern grove.",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "qs-end-decline",
        type: "action",
        position: { x: 200, y: 640 },
        data: {
          actionType: "end",
          label: "End — Declined",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "qs-end-accept",
        type: "action",
        position: { x: -200, y: 960 },
        data: {
          actionType: "end",
          label: "End — Quest Active",
          attributeSchema: [],
          attributes: {},
        },
      },
    ] as SerialNode[],
    edges: [
      {
        id: "qs-e1",
        source: "qs-start",
        target: "qs-npc1",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "qs-e2",
        source: "qs-npc1",
        target: "qs-branch",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "qs-e3",
        source: "qs-branch",
        target: "qs-accept",
        type: "dialogue",
        data: { optionText: "Accept", conditions: {}, metadata: {} },
      },
      {
        id: "qs-e4",
        source: "qs-branch",
        target: "qs-decline",
        type: "dialogue",
        data: { optionText: "Decline", conditions: {}, metadata: {} },
      },
      {
        id: "qs-e5",
        source: "qs-accept",
        target: "qs-trig-accept",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "qs-e6",
        source: "qs-trig-accept",
        target: "qs-npc2",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "qs-e7",
        source: "qs-npc2",
        target: "qs-end-accept",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "qs-e8",
        source: "qs-decline",
        target: "qs-end-decline",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
    ] as SerialEdge[],
  },

  /* ── Shop System ─────────────────────────────────────────── */
  {
    id: "shop-system",
    name: "Shop System",
    description: "Merchant dialogue with UI trigger usage",
    tags: ["start", "trigger", "ui", "branch"],
    nodes: [
      {
        id: "sh-start",
        type: "start",
        position: { x: 0, y: 0 },
        data: { name: "Merchant" },
      },
      {
        id: "sh-merch",
        type: "character",
        position: { x: 0, y: 160 },
        data: {
          name: "Merchant",
          dialogue: "Welcome to my shop! What can I do for you today?",
          emotion: "happy",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "sh-branch",
        type: "action",
        position: { x: 0, y: 320 },
        data: {
          actionType: "branch",
          label: "Customer Choice",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "sh-buy",
        type: "character",
        position: { x: -240, y: 480 },
        data: {
          name: "Hero",
          dialogue: "I'd like to browse your inventory.",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "sh-sell",
        type: "character",
        position: { x: 0, y: 480 },
        data: {
          name: "Hero",
          dialogue: "I have some items to sell.",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "sh-leave",
        type: "character",
        position: { x: 240, y: 480 },
        data: {
          name: "Hero",
          dialogue: "Just passing through. Goodbye.",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "sh-trig-buy",
        type: "action",
        position: { x: -240, y: 640 },
        data: {
          actionType: "trigger",
          label: "Open Shop",
          category: "ui",
          event: "ShowShop",
          params: { mode: "buy" },
          executionMode: "immediate",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "sh-trig-sell",
        type: "action",
        position: { x: 0, y: 640 },
        data: {
          actionType: "trigger",
          label: "Open Inventory",
          category: "ui",
          event: "OpenInventory",
          params: { mode: "sell" },
          executionMode: "immediate",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "sh-end-buy",
        type: "action",
        position: { x: -240, y: 800 },
        data: {
          actionType: "end",
          label: "End — Shop Open",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "sh-end-sell",
        type: "action",
        position: { x: 0, y: 800 },
        data: {
          actionType: "end",
          label: "End — Inventory Open",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "sh-end-leave",
        type: "action",
        position: { x: 240, y: 640 },
        data: {
          actionType: "end",
          label: "End — Left Shop",
          attributeSchema: [],
          attributes: {},
        },
      },
    ] as SerialNode[],
    edges: [
      {
        id: "sh-e1",
        source: "sh-start",
        target: "sh-merch",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "sh-e2",
        source: "sh-merch",
        target: "sh-branch",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "sh-e3",
        source: "sh-branch",
        target: "sh-buy",
        type: "dialogue",
        data: { optionText: "Buy", conditions: {}, metadata: {} },
      },
      {
        id: "sh-e4",
        source: "sh-branch",
        target: "sh-sell",
        type: "dialogue",
        data: { optionText: "Sell", conditions: {}, metadata: {} },
      },
      {
        id: "sh-e5",
        source: "sh-branch",
        target: "sh-leave",
        type: "dialogue",
        data: { optionText: "Leave", conditions: {}, metadata: {} },
      },
      {
        id: "sh-e6",
        source: "sh-buy",
        target: "sh-trig-buy",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "sh-e7",
        source: "sh-sell",
        target: "sh-trig-sell",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "sh-e8",
        source: "sh-trig-buy",
        target: "sh-end-buy",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "sh-e9",
        source: "sh-trig-sell",
        target: "sh-end-sell",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
      {
        id: "sh-e10",
        source: "sh-leave",
        target: "sh-end-leave",
        type: "dialogue",
        data: { optionText: "", conditions: {}, metadata: {} },
      },
    ] as SerialEdge[],
  },
];
