import type { SerialNode, SerialEdge } from "@/types";

export interface ProjectTemplate {
  id: string;
  name: string;
  description: string;
  tags: string[];
  nodes: SerialNode[];
  edges: SerialEdge[];
}

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  /* ── NPC Conversation ──────────────────────────────────── */
  {
    id: "npc-conversation",
    name: "NPC Conversation",
    description: "Standard NPC greeting with a player choice",
    tags: ["basic", "choice", "npc"],
    nodes: [
      {
        id: "npc-start",
        type: "start",
        position: { x: 0, y: 0 },
        data: { label: "Start", attributeSchema: [], attributes: {} },
      },
      {
        id: "npc-greeting",
        type: "character",
        position: { x: 0, y: 140 },
        data: {
          name: "Innkeeper",
          dialogue: "Welcome, traveller! Need a room for the night, or can I get you a drink?",
          emotion: "happy",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "npc-branch",
        type: "action",
        position: { x: 0, y: 300 },
        data: {
          actionType: "branch",
          label: "Player choice",
          choices: [
            { id: "c1", text: "A room, please.", target: "" },
            { id: "c2", text: "Just a drink.", target: "" },
            { id: "c3", text: "Never mind.", target: "" },
          ],
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "npc-room",
        type: "character",
        position: { x: -240, y: 480 },
        data: {
          name: "Innkeeper",
          dialogue: "That'll be 5 gold. Follow me, I'll show you to your room.",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "npc-drink",
        type: "character",
        position: { x: 0, y: 480 },
        data: {
          name: "Innkeeper",
          dialogue: "Coming right up! Ale or wine?",
          emotion: "happy",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "npc-bye",
        type: "character",
        position: { x: 240, y: 480 },
        data: {
          name: "Innkeeper",
          dialogue: "Safe travels, then. Come back any time!",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "npc-end",
        type: "action",
        position: { x: 0, y: 640 },
        data: {
          actionType: "end",
          label: "End Conversation",
          attributeSchema: [],
          attributes: {},
        },
      },
    ] as SerialNode[],
    edges: [
      { id: "npc-e1", source: "npc-start", target: "npc-greeting", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "npc-e2", source: "npc-greeting", target: "npc-branch", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "npc-e3", source: "npc-branch", target: "npc-room", type: "dialogue", data: { optionText: "A room, please.", conditions: {}, metadata: {} } },
      { id: "npc-e4", source: "npc-branch", target: "npc-drink", type: "dialogue", data: { optionText: "Just a drink.", conditions: {}, metadata: {} } },
      { id: "npc-e5", source: "npc-branch", target: "npc-bye", type: "dialogue", data: { optionText: "Never mind.", conditions: {}, metadata: {} } },
      { id: "npc-e6", source: "npc-room", target: "npc-end", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "npc-e7", source: "npc-drink", target: "npc-end", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "npc-e8", source: "npc-bye", target: "npc-end", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
    ] as SerialEdge[],
  },

  /* ── Quest Giver ───────────────────────────────────────── */
  {
    id: "quest-giver",
    name: "Quest Giver",
    description: "Quest offer with accept / decline branching",
    tags: ["quest", "branch", "choice"],
    nodes: [
      {
        id: "qg-start",
        type: "start",
        position: { x: 0, y: 0 },
        data: { label: "Start", attributeSchema: [], attributes: {} },
      },
      {
        id: "qg-intro",
        type: "character",
        position: { x: 0, y: 140 },
        data: {
          name: "Elder Maren",
          dialogue: "Thank the gods you've come! Our village has been plagued by wolves these past weeks. Please, will you help us?",
          emotion: "worried",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "qg-choice",
        type: "action",
        position: { x: 0, y: 300 },
        data: {
          actionType: "branch",
          label: "Accept quest?",
          choices: [
            { id: "c1", text: "I'll handle it.", target: "" },
            { id: "c2", text: "Tell me more.", target: "" },
            { id: "c3", text: "I can't right now.", target: "" },
          ],
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "qg-accept",
        type: "character",
        position: { x: -280, y: 480 },
        data: {
          name: "Elder Maren",
          dialogue: "Bless you! The wolves den in the Thornwood, east of the mill. Return when they trouble us no more.",
          emotion: "relieved",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "qg-details",
        type: "character",
        position: { x: 0, y: 480 },
        data: {
          name: "Elder Maren",
          dialogue: "They've taken two of our sheep and injured a farmhand. The pack seems to be led by a large grey wolf.",
          emotion: "worried",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "qg-decline",
        type: "character",
        position: { x: 280, y: 480 },
        data: {
          name: "Elder Maren",
          dialogue: "I understand. Please, if you change your mind — we have little left to offer, but we'd give everything.",
          emotion: "sad",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "qg-quest-start",
        type: "action",
        position: { x: -280, y: 640 },
        data: {
          actionType: "trigger",
          triggerCategory: "game",
          label: "Quest: Wolves of Thornwood",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "qg-end",
        type: "action",
        position: { x: 0, y: 640 },
        data: {
          actionType: "end",
          label: "End Conversation",
          attributeSchema: [],
          attributes: {},
        },
      },
    ] as SerialNode[],
    edges: [
      { id: "qg-e1", source: "qg-start", target: "qg-intro", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "qg-e2", source: "qg-intro", target: "qg-choice", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "qg-e3", source: "qg-choice", target: "qg-accept", type: "dialogue", data: { optionText: "I'll handle it.", conditions: {}, metadata: {} } },
      { id: "qg-e4", source: "qg-choice", target: "qg-details", type: "dialogue", data: { optionText: "Tell me more.", conditions: {}, metadata: {} } },
      { id: "qg-e5", source: "qg-choice", target: "qg-decline", type: "dialogue", data: { optionText: "I can't right now.", conditions: {}, metadata: {} } },
      { id: "qg-e6", source: "qg-accept", target: "qg-quest-start", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "qg-e7", source: "qg-details", target: "qg-choice", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "qg-e8", source: "qg-decline", target: "qg-end", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "qg-e9", source: "qg-quest-start", target: "qg-end", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
    ] as SerialEdge[],
  },

  /* ── Merchant ──────────────────────────────────────────── */
  {
    id: "merchant",
    name: "Merchant",
    description: "Shop dialogue with haggle and browsing",
    tags: ["shop", "branch", "choice"],
    nodes: [
      {
        id: "mr-start",
        type: "start",
        position: { x: 0, y: 0 },
        data: { label: "Start", attributeSchema: [], attributes: {} },
      },
      {
        id: "mr-greet",
        type: "character",
        position: { x: 0, y: 140 },
        data: {
          name: "Torvin the Trader",
          dialogue: "Finest wares in the realm! Potions, scrolls, and exotic curios — all at a fair price.",
          emotion: "happy",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "mr-choice",
        type: "action",
        position: { x: 0, y: 300 },
        data: {
          actionType: "branch",
          label: "What do you want?",
          choices: [
            { id: "c1", text: "Show me your wares.", target: "" },
            { id: "c2", text: "Can you lower the price?", target: "" },
            { id: "c3", text: "Just browsing.", target: "" },
          ],
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "mr-shop",
        type: "action",
        position: { x: -280, y: 480 },
        data: {
          actionType: "trigger",
          triggerCategory: "ui",
          label: "Open Shop UI",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "mr-haggle",
        type: "character",
        position: { x: 0, y: 480 },
        data: {
          name: "Torvin the Trader",
          dialogue: "Ha! I'm barely breaking even as it is. Tell you what — bring me a wolf pelt and I'll knock 10% off your next purchase.",
          emotion: "amused",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "mr-browse",
        type: "character",
        position: { x: 280, y: 480 },
        data: {
          name: "Torvin the Trader",
          dialogue: "Take your time, no pressure. I'll be here if anything catches your eye.",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "mr-end",
        type: "action",
        position: { x: 0, y: 640 },
        data: {
          actionType: "end",
          label: "End Conversation",
          attributeSchema: [],
          attributes: {},
        },
      },
    ] as SerialNode[],
    edges: [
      { id: "mr-e1", source: "mr-start", target: "mr-greet", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "mr-e2", source: "mr-greet", target: "mr-choice", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "mr-e3", source: "mr-choice", target: "mr-shop", type: "dialogue", data: { optionText: "Show me your wares.", conditions: {}, metadata: {} } },
      { id: "mr-e4", source: "mr-choice", target: "mr-haggle", type: "dialogue", data: { optionText: "Can you lower the price?", conditions: {}, metadata: {} } },
      { id: "mr-e5", source: "mr-choice", target: "mr-browse", type: "dialogue", data: { optionText: "Just browsing.", conditions: {}, metadata: {} } },
      { id: "mr-e6", source: "mr-shop", target: "mr-end", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "mr-e7", source: "mr-haggle", target: "mr-end", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "mr-e8", source: "mr-browse", target: "mr-end", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
    ] as SerialEdge[],
  },

  /* ── Combat Encounter ──────────────────────────────────── */
  {
    id: "combat-encounter",
    name: "Combat Encounter",
    description: "Pre-combat taunt, fight trigger, victory/defeat branches",
    tags: ["combat", "branch", "trigger"],
    nodes: [
      {
        id: "ce-start",
        type: "start",
        position: { x: 0, y: 0 },
        data: { label: "Encounter Start", attributeSchema: [], attributes: {} },
      },
      {
        id: "ce-taunt",
        type: "character",
        position: { x: 0, y: 140 },
        data: {
          name: "Bandit Captain",
          dialogue: "End of the road, stranger. Hand over your coin and maybe I let you walk away.",
          emotion: "aggressive",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "ce-choice",
        type: "action",
        position: { x: 0, y: 300 },
        data: {
          actionType: "branch",
          label: "Player response",
          choices: [
            { id: "c1", text: "I'll never surrender!", target: "" },
            { id: "c2", text: "[Intimidate] Back down, or else.", target: "" },
            { id: "c3", text: "Fine, take it.", target: "" },
          ],
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "ce-fight",
        type: "action",
        position: { x: -280, y: 480 },
        data: {
          actionType: "trigger",
          triggerCategory: "game",
          label: "Start Combat",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "ce-intimidate-win",
        type: "character",
        position: { x: 0, y: 480 },
        data: {
          name: "Bandit Captain",
          dialogue: "...You've got death in your eyes. Lads, we're done here.",
          emotion: "fearful",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "ce-surrender",
        type: "character",
        position: { x: 280, y: 480 },
        data: {
          name: "Bandit Captain",
          dialogue: "Smart choice. Now get out of my sight.",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "ce-victory",
        type: "character",
        position: { x: -280, y: 640 },
        data: {
          name: "Bandit Captain",
          dialogue: "Ugh… I yield! Just spare me, please!",
          emotion: "defeated",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "ce-end",
        type: "action",
        position: { x: 0, y: 800 },
        data: {
          actionType: "end",
          label: "Scene End",
          attributeSchema: [],
          attributes: {},
        },
      },
    ] as SerialNode[],
    edges: [
      { id: "ce-e1", source: "ce-start", target: "ce-taunt", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "ce-e2", source: "ce-taunt", target: "ce-choice", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "ce-e3", source: "ce-choice", target: "ce-fight", type: "dialogue", data: { optionText: "I'll never surrender!", conditions: {}, metadata: {} } },
      { id: "ce-e4", source: "ce-choice", target: "ce-intimidate-win", type: "dialogue", data: { optionText: "[Intimidate] Back down, or else.", conditions: {}, metadata: {} } },
      { id: "ce-e5", source: "ce-choice", target: "ce-surrender", type: "dialogue", data: { optionText: "Fine, take it.", conditions: {}, metadata: {} } },
      { id: "ce-e6", source: "ce-fight", target: "ce-victory", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "ce-e7", source: "ce-intimidate-win", target: "ce-end", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "ce-e8", source: "ce-surrender", target: "ce-end", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "ce-e9", source: "ce-victory", target: "ce-end", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
    ] as SerialEdge[],
  },

  /* ── Companion Dialogue ────────────────────────────────── */
  {
    id: "companion-dialogue",
    name: "Companion Dialogue",
    description: "Relationship-deepening conversation with a party member",
    tags: ["companion", "relationship", "branch"],
    nodes: [
      {
        id: "cd-start",
        type: "start",
        position: { x: 0, y: 0 },
        data: { label: "Camp Conversation", attributeSchema: [], attributes: {} },
      },
      {
        id: "cd-open",
        type: "character",
        position: { x: 0, y: 140 },
        data: {
          name: "Lyra",
          dialogue: "You've been staring at that fire for a while. Mind if I join you?",
          emotion: "curious",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cd-choice1",
        type: "action",
        position: { x: 0, y: 300 },
        data: {
          actionType: "branch",
          label: "Player response",
          choices: [
            { id: "c1", text: "Please, sit.", target: "" },
            { id: "c2", text: "I could use some company.", target: "" },
            { id: "c3", text: "I'd rather be alone.", target: "" },
          ],
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cd-warm",
        type: "character",
        position: { x: -240, y: 480 },
        data: {
          name: "Lyra",
          dialogue: "I've been thinking about what you said back in Ashford. You really meant that, didn't you?",
          emotion: "thoughtful",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cd-company",
        type: "character",
        position: { x: 0, y: 480 },
        data: {
          name: "Lyra",
          dialogue: "I know what it is to feel alone in a crowd. You don't have to carry it all yourself, you know.",
          emotion: "empathetic",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cd-leave",
        type: "character",
        position: { x: 240, y: 480 },
        data: {
          name: "Lyra",
          dialogue: "Of course. I'm here if you change your mind.",
          emotion: "understanding",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cd-bond",
        type: "action",
        position: { x: -120, y: 640 },
        data: {
          actionType: "trigger",
          triggerCategory: "game",
          label: "Companion Bond +1",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cd-end",
        type: "action",
        position: { x: 0, y: 800 },
        data: {
          actionType: "end",
          label: "End Conversation",
          attributeSchema: [],
          attributes: {},
        },
      },
    ] as SerialNode[],
    edges: [
      { id: "cd-e1", source: "cd-start", target: "cd-open", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "cd-e2", source: "cd-open", target: "cd-choice1", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "cd-e3", source: "cd-choice1", target: "cd-warm", type: "dialogue", data: { optionText: "Please, sit.", conditions: {}, metadata: {} } },
      { id: "cd-e4", source: "cd-choice1", target: "cd-company", type: "dialogue", data: { optionText: "I could use some company.", conditions: {}, metadata: {} } },
      { id: "cd-e5", source: "cd-choice1", target: "cd-leave", type: "dialogue", data: { optionText: "I'd rather be alone.", conditions: {}, metadata: {} } },
      { id: "cd-e6", source: "cd-warm", target: "cd-bond", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "cd-e7", source: "cd-company", target: "cd-bond", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "cd-e8", source: "cd-leave", target: "cd-end", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "cd-e9", source: "cd-bond", target: "cd-end", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
    ] as SerialEdge[],
  },

  /* ── Tutorial ──────────────────────────────────────────── */
  {
    id: "tutorial",
    name: "Tutorial Sequence",
    description: "Step-by-step onboarding with UI triggers",
    tags: ["tutorial", "linear", "trigger"],
    nodes: [
      {
        id: "tut-start",
        type: "start",
        position: { x: 0, y: 0 },
        data: { label: "Tutorial Start", attributeSchema: [], attributes: {} },
      },
      {
        id: "tut-welcome",
        type: "character",
        position: { x: 0, y: 140 },
        data: {
          name: "Guide",
          dialogue: "Welcome to the kingdom! I'm your guide. Let me show you the basics before you head out.",
          emotion: "friendly",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "tut-move",
        type: "action",
        position: { x: 0, y: 300 },
        data: {
          actionType: "trigger",
          triggerCategory: "ui",
          label: "Highlight: Movement Controls",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "tut-move-hint",
        type: "character",
        position: { x: 0, y: 460 },
        data: {
          name: "Guide",
          dialogue: "Use WASD or the arrow keys to move. Click to interact with objects highlighted in gold.",
          emotion: "instructive",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "tut-combat",
        type: "action",
        position: { x: 0, y: 620 },
        data: {
          actionType: "trigger",
          triggerCategory: "ui",
          label: "Highlight: Combat Button",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "tut-combat-hint",
        type: "character",
        position: { x: 0, y: 780 },
        data: {
          name: "Guide",
          dialogue: "When enemies are near, this button lights up. Click it to enter combat stance and defend yourself.",
          emotion: "instructive",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "tut-complete",
        type: "action",
        position: { x: 0, y: 940 },
        data: {
          actionType: "trigger",
          triggerCategory: "game",
          label: "Mark Tutorial Complete",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "tut-end",
        type: "action",
        position: { x: 0, y: 1100 },
        data: {
          actionType: "end",
          label: "Begin Adventure",
          attributeSchema: [],
          attributes: {},
        },
      },
    ] as SerialNode[],
    edges: [
      { id: "tut-e1", source: "tut-start", target: "tut-welcome", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "tut-e2", source: "tut-welcome", target: "tut-move", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "tut-e3", source: "tut-move", target: "tut-move-hint", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "tut-e4", source: "tut-move-hint", target: "tut-combat", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "tut-e5", source: "tut-combat", target: "tut-combat-hint", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "tut-e6", source: "tut-combat-hint", target: "tut-complete", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "tut-e7", source: "tut-complete", target: "tut-end", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
    ] as SerialEdge[],
  },

  /* ── Cutscene ──────────────────────────────────────────── */
  {
    id: "cutscene",
    name: "Cutscene",
    description: "Cinematic story moment with audio and camera triggers",
    tags: ["cutscene", "linear", "trigger", "audio"],
    nodes: [
      {
        id: "cs-start",
        type: "start",
        position: { x: 0, y: 0 },
        data: { label: "Cutscene Start", attributeSchema: [], attributes: {} },
      },
      {
        id: "cs-fade",
        type: "action",
        position: { x: 0, y: 140 },
        data: {
          actionType: "trigger",
          triggerCategory: "ui",
          label: "Fade to Black",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cs-music",
        type: "action",
        position: { x: 0, y: 300 },
        data: {
          actionType: "trigger",
          triggerCategory: "audio",
          label: "Play: Revelation Theme",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cs-narrator",
        type: "character",
        position: { x: 0, y: 460 },
        data: {
          name: "Narrator",
          dialogue: "Three years had passed since the fall of the citadel. The world had changed — but not the pain.",
          emotion: "somber",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cs-reveal",
        type: "character",
        position: { x: 0, y: 620 },
        data: {
          name: "Seline",
          dialogue: "You came back. After everything… you actually came back.",
          emotion: "shocked",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cs-response",
        type: "character",
        position: { x: 0, y: 780 },
        data: {
          name: "Player",
          dialogue: "I made you a promise. I keep my promises.",
          emotion: "resolute",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cs-fade-in",
        type: "action",
        position: { x: 0, y: 940 },
        data: {
          actionType: "trigger",
          triggerCategory: "ui",
          label: "Fade In — New Scene",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "cs-end",
        type: "action",
        position: { x: 0, y: 1100 },
        data: {
          actionType: "end",
          label: "Continue to Gameplay",
          attributeSchema: [],
          attributes: {},
        },
      },
    ] as SerialNode[],
    edges: [
      { id: "cs-e1", source: "cs-start", target: "cs-fade", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "cs-e2", source: "cs-fade", target: "cs-music", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "cs-e3", source: "cs-music", target: "cs-narrator", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "cs-e4", source: "cs-narrator", target: "cs-reveal", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "cs-e5", source: "cs-reveal", target: "cs-response", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "cs-e6", source: "cs-response", target: "cs-fade-in", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "cs-e7", source: "cs-fade-in", target: "cs-end", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
    ] as SerialEdge[],
  },

  /* ── Multi-Entry RPG ───────────────────────────────────── */
  {
    id: "multi-entry-rpg",
    name: "Multi-Entry RPG",
    description: "Multiple start points for chapters or conditional entries",
    tags: ["multi-entry", "branch", "jump"],
    nodes: [
      {
        id: "me-s1",
        type: "start",
        position: { x: -320, y: 0 },
        data: { label: "Chapter 1 Entry", attributeSchema: [], attributes: {} },
      },
      {
        id: "me-s2",
        type: "start",
        position: { x: 0, y: 0 },
        data: { label: "Chapter 2 Entry", attributeSchema: [], attributes: {} },
      },
      {
        id: "me-s3",
        type: "start",
        position: { x: 320, y: 0 },
        data: { label: "Chapter 3 Entry", attributeSchema: [], attributes: {} },
      },
      {
        id: "me-ch1",
        type: "character",
        position: { x: -320, y: 160 },
        data: {
          name: "Herald",
          dialogue: "The kingdom is at peace. For now. But rumours of unrest stir in the eastern provinces.",
          emotion: "neutral",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "me-ch2",
        type: "character",
        position: { x: 0, y: 160 },
        data: {
          name: "General",
          dialogue: "The battle is won, but the war rages on. Report to the command tent immediately.",
          emotion: "urgent",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "me-ch3",
        type: "character",
        position: { x: 320, y: 160 },
        data: {
          name: "Oracle",
          dialogue: "You've come far, traveller. The final trial awaits beyond these doors.",
          emotion: "mysterious",
          portrait: "",
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "me-hub",
        type: "action",
        position: { x: 0, y: 360 },
        data: {
          actionType: "branch",
          label: "Scene fork",
          choices: [
            { id: "c1", text: "Investigate the east.", target: "" },
            { id: "c2", text: "Report to command.", target: "" },
            { id: "c3", text: "Enter the final trial.", target: "" },
          ],
          attributeSchema: [],
          attributes: {},
        },
      },
      {
        id: "me-end1",
        type: "action",
        position: { x: -320, y: 540 },
        data: { actionType: "end", label: "End: Chapter 1", attributeSchema: [], attributes: {} },
      },
      {
        id: "me-end2",
        type: "action",
        position: { x: 0, y: 540 },
        data: { actionType: "end", label: "End: Chapter 2", attributeSchema: [], attributes: {} },
      },
      {
        id: "me-end3",
        type: "action",
        position: { x: 320, y: 540 },
        data: { actionType: "end", label: "End: Chapter 3", attributeSchema: [], attributes: {} },
      },
    ] as SerialNode[],
    edges: [
      { id: "me-e1", source: "me-s1", target: "me-ch1", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "me-e2", source: "me-s2", target: "me-ch2", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "me-e3", source: "me-s3", target: "me-ch3", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "me-e4", source: "me-ch1", target: "me-hub", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "me-e5", source: "me-ch2", target: "me-hub", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "me-e6", source: "me-ch3", target: "me-hub", type: "dialogue", data: { optionText: "", conditions: {}, metadata: {} } },
      { id: "me-e7", source: "me-hub", target: "me-end1", type: "dialogue", data: { optionText: "Investigate the east.", conditions: {}, metadata: {} } },
      { id: "me-e8", source: "me-hub", target: "me-end2", type: "dialogue", data: { optionText: "Report to command.", conditions: {}, metadata: {} } },
      { id: "me-e9", source: "me-hub", target: "me-end3", type: "dialogue", data: { optionText: "Enter the final trial.", conditions: {}, metadata: {} } },
    ] as SerialEdge[],
  },
];
